name: CI

on:
  push:
    branches: [ main, flask ]
  pull_request:
    branches: [ main, flask ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Run tests with coverage
        env:
          LOG_LEVEL: INFO
          ENV: test
          SECRET_KEY: test-ci
        run: |
          uv run pytest -q -p no:cacheprovider --cov=food-recipe-recommender/app --cov-report=xml:coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: food-recipe-recommender/app/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: food-recipe-recommender/app/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests with coverage
        run: npm run test:run

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage/lcov.info
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
