name: CI

on:
  push:
    branches: [ main, flask ]
  pull_request:
    branches: [ main, flask ]

permissions:
  contents: read

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync

      - name: Run pytest with coverage
        env:
          LOG_LEVEL: INFO
          ENV: test
          SECRET_KEY: test-ci
          # DATABASE_URL is set by tests/conftest.py if not present; set explicitly for safety
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          uv run pytest -q -p no:cacheprovider --cov=food-recipe-recommender/app --cov-report=xml:coverage.xml

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: food-recipe-recommender/app/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: food-recipe-recommender/app/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run vitest with coverage
        run: npm run test:run

      - name: Build frontend for production
        run: npm run build

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: food-recipe-recommender/app/frontend/coverage/lcov.info
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: recipe-recommender:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

